log:
  level: "INFO"
  format: "[%(asctime)s] [%(levelname)s] [%(name)s]: %(message)s"
  levels:
    wan_manager: "DEBUG"
sabnzbd:
  api_key: "Set env variable SABNZBD_API_KEY"
  base_url: "http://localhost:8080/sabnzbd"
